openapi: "3.0.2"
info:
  title: API Posyandu Melati
  version: "1.0"
  description: API ini digunakan untuk mengakses data dan mengelola data dari web posyandu melati
servers:
  - url: http://localhost:8000/api
tags:
  - name: Data acara
    description: Untuk mengelola data berita acara
  - name: Data komentar
    description: Untuk mengelola data komentar dari berita acara
paths:
  /acara:
    get:
      tags:
        - Data acara
      summary: Untuk mendapatkan data berita acara
      parameters:
        - name: id_acara
          in: query
          description: Data primari dari tabel acara
          schema:
            type: integer
            nullable: true

        - name: length
          in: query
          description: Jumlah item yang akan ditampilkan
          schema:
            type: number
            nullable: true

        - name: start
          in: query
          description: Mengatur ingin memulai pengambilan data dari urutan keberapa
          schema:
            type: number
            nullable: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  draw:
                    type: number
                  recordTotal:
                    type: number
                  recordFiltered:
                    type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id_acara:
                          type: integer
                        judul:
                          type: string
                        isi:
                          type: string
                        kapasitas_peserta:
                          type: integer
                        email_admin:
                          type: string
                        gambar_acara:
                          type: string
                        tanggal_acara:
                          type: string
  /komentar-acara:
    get:
      tags:
        - Data komentar
      summary: Untuk mendapatkan data komentar dari berita acara
      parameters:
        - name: id_komentar_acara
          in: query
          description: Mengambil data spesifik berdasarkan primary key
          schema:
            type: integer
            nullable: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  draw:
                    type: number
                  recordTotal:
                    type: number
                  recordFiltered:
                    type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id_komentar_acara:
                          type: integer
                        id_acara:
                          type: integer
                        id_user:
                          type: integer
                        isi_komentar:
                          type: string
